#!/bin/bash

echo "╔════════════════════════════════════════════════════════════╗"
echo "║        ⚠️  THIS REPOSITORY HAS MOVED ⚠️                    ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "⛔ This installer will NOT work correctly!"
echo ""
echo "This project has been migrated to Codeberg and requires"
echo "files from the new repository to install properly."
echo ""
echo "📍 New location:"
echo "   https://codeberg.org/justaguylinux/i3-setup"
echo ""
echo "To install correctly:"
echo ""
echo "   cd ~"
echo "   git clone https://codeberg.org/justaguylinux/i3-setup"
echo "   cd i3-setup"
echo "   ./install.sh"
echo ""
echo "All future updates happen at the new location."
echo ""
exit 1
